### ISSUE TITLE
To-Dos For Updating  to a Major Version

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/manymome#3]
# To-Dos
- [ ] Check the documentation of new functions.
- [ ] Check the documentation of old functions.
- [ ] Check the documentation of functions: Are all classes documented?
- [ ] Proofread the examples.
- [ ] Proofread the vignettes.
- [ ] Update NEWS.
- [ ] Update DESCRIPTION.
- [ ] Test by `testthat`.
- [ ] Check by `pkgdown::build_site()`
- [ ] Check by `devtools::check()`.
